Repository brave/brave-ui, pull requests merged in 2018-08, with the labels that each got.

#73 Use typescript 3 in order to support React defaultProps cleanly
  package-lock.json
  package.json
Labels: TypeScript

#96 Optimizing story SVGs
  stories/assets/img/ddgo_siteBanner.svg
  stories/assets/img/icn-arrow.svg
  stories/assets/img/lion_logo.svg
  stories/assets/img/private_tab_pagearea_ddgicon.svg
  stories/assets/img/private_tab_pagearea_icon.svg
  stories/assets/img/rewards_ads.svg
  stories/assets/img/rewards_contribute.svg
  stories/assets/img/rewards_donate.svg
  stories/assets/img/rewards_funds.svg
  stories/assets/img/rewards_wallet.svg
  stories/assets/img/welcomebg.svg
Labels: PR/pending-review

#67 add card component
  src/components/index.ts
  src/components/layout/card/__snapshots__/spec.tsx.snap
  src/components/layout/card/index.tsx
  src/components/layout/card/spec.tsx
  src/components/layout/card/style.ts
  stories/components/layout.tsx
  stories/features/welcome/page/index.tsx
  stories/features/welcome/page/theme.ts
Labels: component/panel

#69 add input component
  src/components/formControls/input/__snapshots__/spec.tsx.snap
  src/components/formControls/input/index.tsx
  src/components/formControls/input/spec.tsx
  src/components/formControls/input/style.ts
  src/components/index.ts
  stories/components/formControls.tsx
Labels: component/input

#88 panelWelcome component
  src/features/rewards/index.ts
  src/features/rewards/panelWelcome/__snapshots__/spec.tsx.snap
  src/features/rewards/panelWelcome/assets/batOutline.svg
  src/features/rewards/panelWelcome/index.tsx
  src/features/rewards/panelWelcome/spec.tsx
  src/features/rewards/panelWelcome/style.ts
  stories/assets/locale.ts
  stories/features/rewards/concepts.tsx
  stories/features/rewards/other.tsx
Labels: PR/pending-review

#68 add heading component back to the main component structure
  .storybook/manager-head.html
  src/components/index.ts
  src/components/text/heading/__snapshots__/spec.tsx.snap
  src/components/text/heading/index.tsx
  src/components/text/heading/spec.tsx
  src/components/text/heading/style.ts
  stories/components/text.tsx
Labels: component/heading

#80 WalletPanel component
  src/components/formControls/toggle/__snapshots__/spec.tsx.snap
  src/components/formControls/toggle/style.ts
  src/components/icons/alert-circle.tsx
  src/components/icons/index.tsx
  src/features/rewards/alert/index.tsx
  src/features/rewards/index.ts
  src/features/rewards/mainToggle/__snapshots__/spec.tsx.snap
  src/features/rewards/modalActivity/index.tsx
  src/features/rewards/profile/style.ts
  src/features/rewards/tip/__snapshots__/spec.tsx.snap
  src/features/rewards/toggleTips/__snapshots__/spec.tsx.snap
  src/features/rewards/toggleTips/assets/twitch.tsx
  src/features/rewards/toggleTips/assets/twitter.tsx
  src/features/rewards/toggleTips/assets/youtube.tsx
  src/features/rewards/toggleTips/index.tsx
  src/features/rewards/toggleTips/spec.tsx
  src/features/rewards/toggleTips/style.ts
  src/features/rewards/tokens/index.tsx
  src/features/rewards/tokens/style.ts
  src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
  src/features/rewards/walletPanel/index.tsx
  src/features/rewards/walletPanel/spec.tsx
  src/features/rewards/walletPanel/style.ts
  src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
  src/features/rewards/walletSummary/index.tsx
  src/features/rewards/walletSummary/style.ts
  src/features/rewards/walletSummarySlider/__snapshots__/spec.tsx.snap
  src/features/rewards/walletSummarySlider/index.tsx
  src/features/rewards/walletSummarySlider/spec.tsx
  src/features/rewards/walletSummarySlider/style.ts
  src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap
  src/features/rewards/walletWrapper/index.tsx
  src/features/rewards/walletWrapper/style.ts
  stories/assets/locale.ts
  stories/features/rewards/concepts.tsx
  stories/features/rewards/other.tsx
  stories/features/rewards/settings/pageWallet.tsx
  stories/features/rewards/wallet.tsx
Labels: PR/pending-review

#115 Adding showAllContents prop to Select
  src/components/formControls/select/index.tsx
  src/components/formControls/select/style.ts
  src/features/rewards/walletPanel/index.tsx
  src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap
  src/features/rewards/walletWrapper/style.ts
Labels: PR/pending-review

#117 Replaces assets with icons
  src/features/rewards/donate/__snapshots__/spec.tsx.snap
  src/features/rewards/donate/assets/send.tsx
  src/features/rewards/donate/index.tsx
  src/features/rewards/donate/style.ts
  src/features/rewards/grantClaim/__snapshots__/spec.tsx.snap
  src/features/rewards/grantClaim/assets/gift.tsx
  src/features/rewards/grantClaim/index.tsx
  src/features/rewards/grantClaim/style.ts
  src/features/rewards/modalAddFunds/assets/BAT.svg
  src/features/rewards/modalAddFunds/assets/BTC.svg
  src/features/rewards/modalAddFunds/assets/ETH.svg
  src/features/rewards/modalAddFunds/assets/LTC.svg
  src/features/rewards/modalAddFunds/index.tsx
  src/features/rewards/modalAddFunds/style.ts
  src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap
  src/features/rewards/siteBanner/assets/twitch.tsx
  src/features/rewards/siteBanner/assets/twitter.tsx
  src/features/rewards/siteBanner/assets/youtube.tsx
  src/features/rewards/siteBanner/index.tsx
  src/features/rewards/siteBanner/style.ts
  src/features/rewards/tip/__snapshots__/spec.tsx.snap
  src/features/rewards/toggleTips/__snapshots__/spec.tsx.snap
  src/features/rewards/toggleTips/assets/twitch.tsx
  src/features/rewards/toggleTips/assets/twitter.tsx
  src/features/rewards/toggleTips/assets/youtube.tsx
  src/features/rewards/toggleTips/index.tsx
  src/features/rewards/toggleTips/style.ts
  stories/features/rewards/settings/pageWallet.tsx
Labels: PR/pending-review
