Repository brave/brave-ui, pull requests merged in 2018-11, with the labels that each got.

#241 Adds new 2 state tab component
  src/features/rewards/index.ts
  src/features/rewards/tab/__snapshots__/spec.tsx.snap
  src/features/rewards/tab/index.tsx
  src/features/rewards/tab/spec.tsx
  src/features/rewards/tab/style.ts
  src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
  stories/features/rewards/other.tsx
Labels: PR/pending-review

#258 Adds subtitle to add funds dialog
  src/features/rewards/modalAddFunds/__snapshots__/spec.tsx.snap
  src/features/rewards/modalAddFunds/index.tsx
  src/features/rewards/modalAddFunds/style.ts
  stories/assets/locale.ts
Labels: rewards

#268 Adding RestoreSites component
  src/features/rewards/index.ts
  src/features/rewards/modalContribute/index.tsx
  src/features/rewards/modalContribute/style.ts
  src/features/rewards/restoreSites/__snapshots__/spec.tsx.snap
  src/features/rewards/restoreSites/index.tsx
  src/features/rewards/restoreSites/spec.tsx
  src/features/rewards/restoreSites/style.ts
  src/features/rewards/tableContribute/index.tsx
  src/features/rewards/tableContribute/style.ts
  stories/assets/locale.ts
  stories/features/rewards/settings/contributeBox.tsx
Labels: PR/pending-review

#249 welcome screen v1.0
  src/features/welcome/background/index.ts
  src/features/welcome/button/index.ts
  src/features/welcome/image/index.ts
  src/features/welcome/index.ts
  src/features/welcome/text/index.ts
  src/features/welcome/wrapper/index.ts
  stories/assets/img/features.png
  stories/assets/img/import.png
  stories/assets/img/payments.png
  stories/assets/img/shields.png
  stories/assets/img/welcome_bg.svg
  stories/assets/img/welcome_import.svg
  stories/assets/img/welcome_rewards.svg
  stories/assets/img/welcome_search.svg
  stories/assets/img/welcome_shields.svg
  stories/assets/img/welcome_theme.svg
  stories/assets/img/welcomebg.svg
  stories/features/welcome/page/fakeLocale.ts
  stories/features/welcome/page/index.tsx
  stories/features/welcome/page/screens/footerBox.tsx
  stories/features/welcome/page/screens/importBox.tsx
  stories/features/welcome/page/screens/rewardsBox.tsx
  stories/features/welcome/page/screens/searchBox.tsx
  stories/features/welcome/page/screens/shieldsBox.tsx
  stories/features/welcome/page/screens/themeBox.tsx
  stories/features/welcome/page/screens/welcomeBox.tsx
  stories/features/welcome/page/theme.ts
  stories/features/welcome/story.tsx
  stories/storyUtils.tsx
Labels: PR/work-in-progress

#255 Mobile siteBanner
  src/features/rewards/amount/__snapshots__/spec.tsx.snap
  src/features/rewards/amount/index.tsx
  src/features/rewards/amount/style.ts
  src/features/rewards/donate/__snapshots__/spec.tsx.snap
  src/features/rewards/donate/index.tsx
  src/features/rewards/donate/style.ts
  src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap
  src/features/rewards/siteBanner/index.tsx
  src/features/rewards/siteBanner/style.ts
  src/features/rewards/tip/__snapshots__/spec.tsx.snap
  stories/features/rewards/concepts.tsx
Labels: PR/pending-review

#275 Android UI Fixes
  src/components/formControls/select/index.tsx
  src/components/formControls/select/style.ts
  src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap
  src/features/rewards/grantComplete/index.tsx
  src/features/rewards/grantComplete/style.ts
  src/features/rewards/profile/__snapshots__/spec.tsx.snap
  src/features/rewards/profile/index.tsx
  src/features/rewards/profile/style.ts
  src/features/rewards/tableContribute/index.tsx
  src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
  src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
  src/features/rewards/welcomePage/style.ts
  stories/features/rewards/settingsMobile/contributeBoxMobile.tsx
  stories/features/rewards/settingsMobile/grantMobile.tsx
Labels: PR/pending-review

#274 Implements cross-platform Backup/Recovery modal
  src/components/formControls/textarea/index.tsx
  src/components/formControls/textarea/style.ts
  src/features/rewards/modalBackupRestore/__snapshots__/spec.tsx.snap
  src/features/rewards/modalBackupRestore/index.tsx
  src/features/rewards/modalBackupRestore/style.ts
  stories/assets/locale.ts
  stories/features/rewards/modal.tsx
  stories/features/rewards/settings/pageWallet.tsx
Labels: PR/pending-review

#283 Adjusting modal button spacing
  src/features/rewards/tipsMigrationAlert/index.tsx
  src/features/rewards/tipsMigrationAlert/style.ts
Labels: PR/pending-review

#290 Restores monthly alignment on desktop
  src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap
  src/features/rewards/siteBanner/style.ts
Labels: PR/pending-review

#292 Changing monthlyAmount prop to string
  src/features/rewards/walletPanel/index.tsx
  stories/features/rewards/concepts.tsx
  stories/features/rewards/wallet.tsx
Labels: PR/pending-review

#296 Fixing fillRule atts
  src/components/icons/arrow-anchor.tsx
  src/components/icons/carat-circle.tsx
  src/components/icons/paper-airplane.tsx
  src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
Labels: PR/pending-review

#294 Adding provider support to siteBanner
  src/features/rewards/siteBanner/index.tsx
  stories/features/rewards/concepts.tsx
Labels: PR/pending-review
